#!/bin/sh

file=$(readlink -f $1)
dir=$(dirname $file)
base=${file%.*}
shebang=$(sed -n 1p $file)

cd $dir || exit

shebang() {
	case $shebang in
		\#\!*) $file ;;
		*) sent $file 2>/dev/null & ;;
	esac	
}

case $file in 
	*\.dot) dot -Tpng -O $file && dot -Tsvg -O $file ;;
	*\.ms) groff $file -pejR -ms -Tpdf > $base.pdf ;;
	*\.me) groff $file -pejR -me -Tpdf > $base.pdf ;;
	*\.mom) groff $file -pejR -mom -Tpdf > $base.pdf ;;
	*\.c) cc -Wall $file -o $base && $base ;;
	*\.cpp) g++ -Wall $file -o $base && $base ;;
	*\.rs) rustc $file -o $base && $base ;;
	*\.m) octave $file ;;
	*\.R) R --vanilla < $file ;;
	*) shebang ;;
esac
