#!/bin/sh

file=$(readlink -f $1)
dir=$(dirname $file)
base=${file%.*}
shebang=$(head -n 1 $file)

cd $dir || exit

shebang() {
	case $shebang in
		\#\!*) $file ;;
		*) sent $file 2>/dev/null & ;;
	esac	
}

case $file in 
	*\.dot) dot -Tpng -O $file && dot -Tsvg -O $file ;;
	*\.ms) groff $file -pejR -ms -Tpdf > $base.pdf ;;
	*\.me) groff $file -pejR -me -Tpdf > $base.pdf ;;
	*\.mom) groff $file -pejR -mom -Tpdf > $base.pdf ;;
	*\.c) cc -Wall -O -pedantic -ansi $file -o $base && $base ;;
	*\.cpp) g++ -Wall $file -o $base && $base ;;
	*\.rs) rustc $file -o $base && $base ;;
	*\.m) octave $file ;;
	*\.R) R --vanilla < $file ;;
	*\.ps1) pwsh -nologo -file $file ;;
	*\.pic) pic $file > $base.ps ;;
	*\.py) python3 $file ;;
	*\.sql) mysql < $file > $base.tab ;;
	*\.s) as $file -o $base.o && ld $base.o -o $base && $base ;;
	*\.asm) nasm -f elf32 -o $base.o $file && ld -m elf_i386 -o $base $base.o && $base ;;
	*\.tf) terraform validate -no-color && terraform plan -no-color -out=$base.tfplan ;;
	*) shebang ;;
esac
