#!/bin/sh

if [ -z "$1" ]; then
	echo "usage: $(basename $0) FILE"
	exit 1
fi

file=$(readlink -f $1)

if [ -z "$file" ]; then
	echo "$1: No such file" >&2
	exit 1
fi

dir=$(dirname $file)
base=${file%.*}
cd $dir || exit 1

shebang=$(head -n 1 $file)
shebang() {
	case $shebang in
		\#\!*) $file ;;
		*) sent $file 2>/dev/null & ;;
	esac	
}

case $file in 
	*\.asm) nasm -f elf32 -o $base.o $file && ld -m elf_i386 -o $base $base.o && $base ;;
	*\.c) cc -Wall -O -pedantic -ansi $file -o $base && $base ;;
	*\.cpp) g++ -Wall $file -o $base && $base ;;
	*\.dot) dot -Tpng -O $file && dot -Tsvg -O $file ;;
	*\.m) octave -q --persist $file ;;
	*\.me) groff $file -pejR -me -Tpdf > $base.pdf ;;
	*\.mom) groff $file -pejR -mom -Tpdf > $base.pdf ;;
	*\.ms) groff $file -pejR -ms -Tpdf > $base.pdf ;;
	*\.pic) pic $file > $base.ps ;;
	*\.ps1) pwsh -nologo -noexit -file $file ;;
	*\.py) ipython3 --no-banner -i $file ;;
	*\.R) R --vanilla < $file ;;
	*\.rs) rustc $file -o $base && $base ;;
	*\.sql) mysql < $file > $base.tab ;;
	*\.s) as $file -o $base.o && ld $base.o -o $base && $base ;;
	*\.tf) terraform validate -no-color && terraform plan -no-color -out=$base.tfplan ;;
	*\.tex) pdflatex $file ;;
	*) shebang ;;
esac
